### ISSUE TITLE
[BUG] Some games using the source engine don't run with the native binaries

### ISSUE THREAD

**Issue by cristobaltapia** [linuxserver/docker-steamos#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing some games using the source engine (e.g. Black Mesa) the game wont start. Running the windows binaries with Proton produces memory errors frequently. The solution is described in the Wiki from Archlinux [1] and consists on installing the package [lib32-gperftools](https://aur.archlinux.org/packages/lib32-gperftools/) from the AUR. The games can then be started with:

```
LD_PRELOAD=/usr/lib32/libtcmalloc_minimal.so %command%
```

The following patch takes care of installing the needed packages:

```patch
diff --git a/Dockerfile b/Dockerfile
index 2f1a104..1ec19a7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -48,11 +48,14 @@ RUN \
     fuse2 \
     gamescope \
     git \
+    gperftools \
     jq \
     kate \
     konsole \
     lib32-gamescope \
+    lib32-gcc-libs \
     lib32-libpulse \
+    lib32-libunwind \
     lib32-mesa-vdpau \
     lib32-opencl-mesa \
     lib32-renderdoc-minimal \
@@ -75,6 +78,13 @@ RUN \
   sed -i '/npm install/i sudo chown -R 911:1001 \/config' PKGBUILD && \
   sudo -u abc makepkg -sAci --skipinteg --noconfirm --needed && \
   usermod -G input abc && \
+  echo "**** install fix for games using source engine ****" && \
+  cd /tmp && \
+  git clone https://aur.archlinux.org/lib32-gperftools.git && \
+  chown -R abc:abc lib32-gperftools && \
+  cd lib32-gperftools && \
+  sudo -u abc makepkg -sAci --skipinteg --noconfirm --needed && \
+  usermod -G input abc && \
   echo "**** steam tweaks ****" && \
   sed -i 's/-steamdeck//g' /usr/bin/steam && \
   echo "**** kde tweaks ****" && \
```

[1] https://wiki.archlinux.org/title/Steam/Game-specific_troubleshooting

### Steps To Reproduce

1. Install Black Mesa (Linux version, i.e. not with Proton)
2. Start the game

### CPU architecture

x86-64

### Docker creation

```bash
(not necessary)
```

### Container logs

```bash
(not necessary)
```

**Comment by thelamer** [comment]
Added thanks for the patch

**Comment by cristobaltapia** [comment]
Great! I'm glad the patch was useful ;)
