### ISSUE TITLE
[BUG] sunshine unable to start:  error while loading shared libraries

### ISSUE THREAD

**Issue by tejpillay** [linuxserver/docker-steamos#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sunshine service doesnt start but steam os goes but unable to use steam link or moonlight
sunshine: error while loading shared libraries: libboost_locale.so.1.81.0: cannot open shared object file: No such file or directory

### Expected Behavior

should be able to use steam link / moonlight

### Steps To Reproduce

  steamos:
    image: lscr.io/linuxserver/steamos:latest
    container_name: steamos
    hostname: test #optional
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DRINODE=/dev/dri/renderD128
      - HOST_IP=192.168.1.3 #optional
      #- STARTUP=BIGPICTURE #optional
      - STARTUP=KDE #optional
      - RESOLUTION=1920x1080 #optional
    volumes:
      - /tmp/config:/config
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 3001:3001
      - 27031-27036:27031-27036/udp #optional
      - 27031-27036:27031-27036 #optional
      - 47984-47990:47984-47990 #optional
      - 48010-48010:48010-48010 #optional
      - 47998-48000:47998-48000/udp #optional
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped

### Environment

```markdown
- OS:  Ubuntu 20.04
- How docker service was installed: apt-get
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up
```

### Container logs

```bash
migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** creating video group video3s1f with id 110 ****
**** adding /dev/dri/renderD128 to video group video3s1f with id 110 ****
**** creating video group videog646 with id 44 ****
**** adding /dev/dri/card0 to video group videog646 with id 44 ****
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Sep 15 2023 16:22:02
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
2023/09/21 15:55:04 [warn] 262#262: could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
Set firefox.desktop as the default for x-scheme-handler/https
Set firefox.desktop as the default for x-scheme-handler/http
sunshine: error while loading shared libraries: libboost_locale.so.1.81.0: cannot open shared object file: No such file or directory
```

**Comment by gsaker** [comment]
I have an identical issue

**Comment by thelamer** [comment]
I have been hoping this would get resolved by now but the fundemental issue is the zst sunshine ships for Arch is out of sync with Arch as it is a rolling distro. (the boost libs are too new in Arch)
I need to get this ingesting from AUR https://aur.archlinux.org/packages/sunshine and build from source at build time, but my overall hope was to bypass sunshine completely and do web native HEVC delivery, I know it is a lofty goal but the gamepad issue along with maintenance makes me think it is the only viable route to keep something like this going. 

I will try for AUR this weekend.

**Comment by thelamer** [comment]
Easier than I thought, building now will be up within the hour.
